### ISSUE TITLE
Facing issue while run your project

### ISSUE THREAD

**Issue by chaitanya666** [mucharafal/jcef_example#1]
![image](https://github.com/mucharafal/jcef_example/assets/30200743/8058e4b8-12e0-4d2b-b0a7-293202fc7bb8)

**Comment by mucharafal** [comment]
Hi, I updated main branch - can you try again? (unfortunately, I don't have access to Windows machine to reproduce the problem).

**Comment by chaitanya666** [comment]
Hi,
It's working fine now, did you done any other examples similar like this, I
have a requirement to implement extension.
Might be if you have anything, it may helps

**Comment by mucharafal** [comment]
Unfortunately no, I haven't done any other example. I can recommend: https://plugins.jetbrains.com/docs/intellij/jcef.html#jbcefjsquery
