### ISSUE TITLE
How to implement communication between IDE and webView? 

### ISSUE THREAD

**Issue by AyushVachaspati** [mucharafal/jcef_example#2]
Hey, 

Thank you so much for this example repo. It's really helpful. Are you aware of any example code which shows how we can pass messages between the IDE and our webView? I want to create my webView in svelte and communicate with the IDE to get user commands, code input etc. I would be really grateful if you could point me in the right direction. 

Thanks in advance! :)

**Comment by mucharafal** [comment]
No, I didn't search it. For communication we used call back mechanism described here:
https://plugins.jetbrains.com/docs/intellij/jcef.html#jbcefjsquery

Best,
Rafal

**Comment by AyushVachaspati** [comment]
Thank you so much for the response. I'll try to use that too, hopefully it'll work.
